install:
	brew install neovim neovim-remote 
	ln -fs ~/Config/neovim/nvim ~/.config/nvim
	ln -fs ~/Config/neovim/clang-format ~/.clang-format
	ln -fs ~/Config/neovim/php-cs-fixer.php ~/.php-cs-fixer.php
	git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
	
install_more:	
	brew install ripgrep fd clang-format bash-language-server shellcheck vscode-langservers-extracted eslint marksman
	pip3 install cmake-language-server jedi-language-server
	npm install -g intelephense


